### ISSUE TITLE
Bi el atar mısınız?

### ISSUE THREAD

**Issue by yasim-doner** [ofenerci/9Sinif-3Odev#3]
Hocam 3.bölümün ilk sorusunu tam anlayamadım orayı biraz açıklayabilir misiniz?

**Comment by ofenerci** [comment]
Yahya,
Zamandaki hatam 1/60 saniye. Bundan daha önceki zamana ait konum bilgisini ölçmem mümkün değil. Konumdaki hatam ise ekrandaki metrenin hassasiyetine ve benim gözüme bağlı. 5mm'den daha hassas ölçemedim. Verilerime dikkat edersen verilerim 5mm'den az değil
